### PR TITLE
Delete reviewee

### PR DESCRIPTION
**Pull request by josephined21**

### CODE REVIEW

**Comment by mattliu-mygit** [comment]
Reviewee.tsx did not pass Prettier. Please fix.

**Review by mattliu-mygit — CHANGES_REQUESTED** [review]
Prettier checks did not pass. Please download the ESLint and Prettier VSCode extensions if you haven't already. ^.^
Then set "Format on Save" to be true. Saving on the file should make file prettier-compliant.

**Review by mattliu-mygit — APPROVED** [review]
Looks good!

**Review by kyang117 — APPROVED** [review]
yes!

**Comment by mattliu-mygit** [comment]
All approved. Merging! Whoooo!

**Pull request merged**
