### PR TITLE
DEV-106 Fix prerequisite issue: EN.990.100 - replacing with Lab Safety, completed by default

### PR DESCRIPTION
**Pull request by nicolasliuu**
Description: Lab courses required the prerequisite EN.990.100 which isn't a real course - it is actually the course code for Lab Safety, which is unintuitive for users. This is an important bug to fix because it improves readability and user-friendliness as the user knows exactly which requirement it is.

Implementation: Checked if the course number corresponded to Lab Safety, if yes, display 'Lab Safety' instead of 'EN.990.100' and defaulted this prerequisite to completed because the user cannot manually complete it.

Testing: Tested locally, works good.

### CODE REVIEW

**Review by josephined21 — CHANGES_REQUESTED** [review]
hi nic! could you make sure prettier passes? tyty~

**Review by aryamanshodhan — CHANGES_REQUESTED** [review]
Looks good! Please make sure Prettier checks pass!

**Review by josephined21 — APPROVED** [review]
looks good to me! great work nic!

**Review by josephined21 — CHANGES_REQUESTED** [review]
pls make sure vercel deployment works!

**Review by josephined21 — APPROVED** [review]
lgtm!

**Pull request merged**
