### PR TITLE
DEV-187: Filter search fine requirement in cart

### PR DESCRIPTION
**Pull request by RosaGao**

### CODE REVIEW

**Review by mpark63 — CHANGES_REQUESTED** [review]
could you describe what this fixes so that I can test locally? 

thanks!

**Comment by RosaGao** [comment]
> could you describe what this fixes so that I can test locally?
> 
> thanks!

sure sure! It's for searching for courses in the fine requirements after clicking from the degree progress bar. Previously the search function didn't work if the user typed and now it should.

**Review by mpark63 — APPROVED** [review]
great! ty rosa!

**Comment by RosaGao** [comment]
Thanks @mpark63! Just merged :)

**Pull request merged**
