### PR TITLE
feat: complete features planned for /reviewer route and integrate frontend with updated backend reviewing logic

### PR DESCRIPTION
**Pull request by robertzhidealx**

### CODE REVIEW

**Review by MattLiu-mygit — CHANGES_REQUESTED** [review]
Plan overview should be show in view-only mode but reviewer list should not. Cart onClick should be disabled as well.

**Comment by robertzhidealx** [comment]
> Plan overview should be show in view-only mode but reviewer list should not. Cart onClick should be disabled as well.

Done

**Review by MattLiu-mygit — APPROVED** [review]
Too lit!

**Review by alanz132 — APPROVED** [review]
Looks good!

**Pull request merged**
