### PR TITLE
DEV-116 fix lowest credit requirement for intersession/summer semester

### PR DESCRIPTION
**Pull request by QifanSun1128**
**Description**
When hovering over the total #credit for Intersession/summer semester, there will be a reminder "More than 3 credits required" for Intersession, and "More than 12 credits required". However, there should be no lowest credit limit for these two semesters.

**Implementation**
In Semester.tsx, deleted the >3 limit and >12 limit for intersession/summer semesters in the trigerring condition for the reminder "More than ... credits" to show up. Also modify the corresponding condition for the background color of the credit to change according to the total number of credits.

**Testing**
Tested locally. Tested with B.S. CS plan. Add 1/2/3/4-credit course in the 4 intersession semesters separately. Hover over the #credit for each of the intersession semester, and the reminder goes away. Now only "# credits" will show up when hovered over. Similar tests are done for the 4 summer semesters.

### CODE REVIEW

**Review by mattliu-mygit — CHANGES_REQUESTED** [review]
Awesome! Looks good! Just check up on the Prettier issues for the Semester component and this should be good to go. ^.^

**Comment by QifanSun1128** [comment]
Done with the formatting of Semester.tsx but the prettier test is still failing. Tried to format other files the tests pointed out with warning but there seems to be no changes made when I run prettier on them.

**Comment by mattliu-mygit** [comment]
All good, approved!

**Review by mattliu-mygit — APPROVED** [review]

**Review by josephined21 — CHANGES_REQUESTED** [review]
Hi Fyona! Could you make sure that Summer is green with any number of credits, like Intersession?
image 
image

**Review by josephined21 — APPROVED** [review]
looks great! thank you fyona :)

**Review by josephined21 — CHANGES_REQUESTED** [review]
hi fyona! could you just make sure that prettier passes? after that you should be good to merge :)

**Review by josephined21 — APPROVED** [review]
yay!

**Pull request merged**
