### PR TITLE
DEV-165: update add course buton

### PR DESCRIPTION
**Pull request by mpark63**
Change color scheme and remove transition. 

https://docs.google.com/presentation/d/1nonjRzYbSahnqKHAa0S-32I5ifZ-qqACYJgIADww6mQ/edit

proposal: 
Screenshot 2023-06-14 at 8 31 19 PM

before: 
Screenshot 2023-06-14 at 8 48 54 PM

after: 
Screenshot 2023-06-14 at 8 48 26 PM

### CODE REVIEW

**Review by josephined21 — APPROVED** [review]
minspog

**Review by josephined21 — CHANGES_REQUESTED** [review]
prettier failing smoge

**Comment by mpark63** [comment]
> prettier failing smoge

says i have nothing to change? maybe my prettier version is off.

**Review by josephined21 — APPROVED** [review]
poggers

**Review by nishikar12 — APPROVED** [review]

**Pull request merged**
