### PR TITLE
Iter 02 backdoor login: set up with local database

### PR DESCRIPTION
**Pull request by JJamesWWang**
Fix experiments infinite loop
Login only has a single mock user, but you can log in with any id now

### CODE REVIEW

**Review by MattLiu-mygit — CHANGES_REQUESTED** [review]
ik it's not your code, but can you resolve the linter errors? should be a super quick update ^.^

**Comment by JJamesWWang** [comment]
Whoever wrote the non-compliant code, I am hunting you down /s

**Comment by JJamesWWang** [comment]
@robertzhidealx my git lens says it was you, what do you have to say for yourself ㅇㅇ

**Review by MattLiu-mygit — APPROVED** [review]
Lit!

**Comment by robertzhidealx** [comment]
> @robertzhidealx my git lens says it was you, what do you have to say for yourself ㅇㅇ

Sorry for that unused variable. I was thinking to use apiUrl in production.

**Review by robertzhidealx — APPROVED** [review]
Looks good

**Review by alanz132 — APPROVED** [review]
Looks great

**Review by DenouementX — APPROVED** [review]
lgtm!

**Pull request merged**
