### PR TITLE
Correct CS minor && BS AMS 

### PR DESCRIPTION
**Pull request by mpark63**
CS minor old & new
- split single bar into multiple distributions 
- allowed users to fulfill focus areas 
BS AMS
- fixed typos & issues with electives

### CODE REVIEW

**Comment by mpark63** [comment]
Hey JJ, I made 1 commit but I think Matt's commits somehow got mixed in this PR haha... Is that okay? I only edited majors.tsx

**Review by kyang117 — APPROVED** [review]
yess

**Comment by kyang117** [comment]
> Hey @kyang117, I made 1 commit but I think Matt's commits somehow got mixed in this PR haha... Is that okay? I only edited majors.tsx

Which of Matt's commits are you talking about? I think I only saw yours. Also, each time you make a PR you should add Matt as a reviewer too! But otherwise it's good for me.

**Comment by mpark63** [comment]
Hey @mattliu-mygit, how to pass the playwright checks?

**Review by mattliu-mygit — APPROVED** [review]
No need to pass Playwright. Looks good!

**Pull request merged**
